server:
  port: 8888
spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      routes:
#        - id: mytest
#          uri: http://ityouknow.com
#          predicates:
#            - After=2020-02-20T06:06:06+08:00[Asia/Shanghai] # ָ ��ʱ��֮�������Ч
#            - Before=2020-12-20T06:06:06+08:00[Asia/Shanghai]   # ָ ��ʱ��֮ǰ������Ч
#            - Between=2020-01-20T06:06:06+08:00[Asia/Shanghai], 2020-12-20T06:06:06+08:00[Asia/Shanghai]  # ָ ��ʱ��η�����Ч
#            - Cookie=ityouknow,kee.e   # ��Я��cookie name��ityouknow  value:kee.e ���޷�����
#            - Header=X-Request-Id,\d+    # ����ͷ= ���� �� ֵ ��������ʽ��
#            - Host=**.ityouknow.com    # ����host��ַ Ҫ xx.ityouknow.com ���ܷ��ʳɹ�
#            - Method=GET     # ����ģʽ
#            - Path=/foo/{id}   # ·��ƥ��
#            - Query=smile      # Я������ smile �˿��Է���
#            - Query=name
#            - Query=smile,c   # Я������ smile �� ֵΪ c �ſ��Է���
#            - RemoteAddr=192.168.1.1/24

        - id: client1
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/client/hello
            - Weight=service1,60

        - id: client2
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/client/hello
            - Weight=service1,60

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



